insert into cnpj.responsavel_qualificacao values (5, "ADMINISTRADOR");
insert into cnpj.responsavel_qualificacao values (10, "DIRETOR");
insert into cnpj.responsavel_qualificacao values (11, "INTERVENTOR");
insert into cnpj.responsavel_qualificacao values (12, "INVENTARIANTE");
insert into cnpj.responsavel_qualificacao values (13, "LIQUIDANTE");
insert into cnpj.responsavel_qualificacao values (16, "PRESIDENTE");
insert into cnpj.responsavel_qualificacao values (17, "PROCURADOR");
insert into cnpj.responsavel_qualificacao values (18, "SECRETÁRIO");
insert into cnpj.responsavel_qualificacao values (19, "SÍNDICO (CONDOMÍNIO)");
insert into cnpj.responsavel_qualificacao values (23, "SÓCIO CAPITALISTA");
insert into cnpj.responsavel_qualificacao values (24, "SÓCIO COMANDITADO");
insert into cnpj.responsavel_qualificacao values (31, "SÓCIO OSTENSIVO");
insert into cnpj.responsavel_qualificacao values (32, "TABELIÃO");
insert into cnpj.responsavel_qualificacao values (33, "TESOUREIRO");
insert into cnpj.responsavel_qualificacao values (34, "TITULAR DE EMPRESA INDIVIDUAL IMOBILIÁRIA");
insert into cnpj.responsavel_qualificacao values (39, "DIPLOMATA");
insert into cnpj.responsavel_qualificacao values (40, "CÔNSUL");
insert into cnpj.responsavel_qualificacao values (41, "REPRESENTANTE DE ORGANIZAÇÃO INTERNACIONAL");
insert into cnpj.responsavel_qualificacao values (42, "OFICIAL DE REGISTRO");
insert into cnpj.responsavel_qualificacao values (43, "RESPONSÁVEL");
insert into cnpj.responsavel_qualificacao values (46, "MINISTRO DE ESTADO DAS RELAÇÕES EXTERIORES");
insert into cnpj.responsavel_qualificacao values (49, "SÓCIO-ADMINISTRADOR");
insert into cnpj.responsavel_qualificacao values (50, "EMPRESÁRIO");
insert into cnpj.responsavel_qualificacao values (51, "CANDIDATO A CARGO POLÍTICO ELETIVO");
insert into cnpj.responsavel_qualificacao values (54, "FUNDADOR");
insert into cnpj.responsavel_qualificacao values (59, "PRODUTOR RURAL");
insert into cnpj.responsavel_qualificacao values (60, "CÔNSUL HONORÁRIO");
insert into cnpj.responsavel_qualificacao values (61, "RESPONSÁVEL INDÍGENA");
insert into cnpj.responsavel_qualificacao values (62, "REPRESENTANTE DA INSTITUIÇÃO EXTRATERRITORIAL");
insert into cnpj.responsavel_qualificacao values (64, "ADMINISTRADOR JUDICIAL");
insert into cnpj.responsavel_qualificacao values (65, "TITULAR PESSOA FÍSICA RESIDENTE OU DOMICILIADO NO BRASIL");
insert into cnpj.responsavel_qualificacao values (77, "VICE-PRESIDENTE");

insert into cnpj.situacao_cadatral_motivo values (1, "EXTINÇÃO POR ENCERRAMENTO LIQUIDAÇÃO VOLUNTÁRIA");
insert into cnpj.situacao_cadatral_motivo values (2, "INCORPORAÇÃO");
insert into cnpj.situacao_cadatral_motivo values (3, "FUSÃO");
insert into cnpj.situacao_cadatral_motivo values (4, "CISÃO TOTAL ");
insert into cnpj.situacao_cadatral_motivo values (5, "ENCERRAMENTO DA FALÊNCIA");
insert into cnpj.situacao_cadatral_motivo values (6, "ENCERRAMENTO DA LIQUIDAÇÃO");
insert into cnpj.situacao_cadatral_motivo values (7, "ELEVAÇÃO A MATRIZ");
insert into cnpj.situacao_cadatral_motivo values (8, "TRANSPASSE ");
insert into cnpj.situacao_cadatral_motivo values (9, "NÃO INÍCIO DE ATIVIDADE");
insert into cnpj.situacao_cadatral_motivo values (10, "EXTINÇÃO PELO ENCERRAMENTO DA LIQUIDAÇÃO JUDICIAL");
insert into cnpj.situacao_cadatral_motivo values (11, "ANULAÇÃO POR MULTICIPLIDADE");
insert into cnpj.situacao_cadatral_motivo values (12, "ANULAÇÃO ONLINE DE OFICIO");
insert into cnpj.situacao_cadatral_motivo values (13, "OMISSA CONTUMAZ");
insert into cnpj.situacao_cadatral_motivo values (14, "OMISSA NÃO LOCALIZADA");
insert into cnpj.situacao_cadatral_motivo values (15, "INEXISTENTE DE FATO");
insert into cnpj.situacao_cadatral_motivo values (16, "ANULAÇÃO POR VÍCIOS");
insert into cnpj.situacao_cadatral_motivo values (17, "BAIXA INICIADA E AINDA NÃO DEFERIDA");
insert into cnpj.situacao_cadatral_motivo values (18, "INTERRUPÇÃO TEMPORÁRIA DAS ATIVIDADES");
insert into cnpj.situacao_cadatral_motivo values (19, "OMISSO DE DIRPJ ATÉ 5 EXERCÍCIOS");
insert into cnpj.situacao_cadatral_motivo values (20, "EM CONDIÇÃO DE INAPTIDÃO");
insert into cnpj.situacao_cadatral_motivo values (21, "PEDIDO DE BAIXA INDEFERIDA");
insert into cnpj.situacao_cadatral_motivo values (22, "RESTABELECIMENTO COM CERTIDÃO POSITIVA COM EFEITO DE NEGATIVA");
insert into cnpj.situacao_cadatral_motivo values (23, "COM PENDÊNCIA FISCAL");
insert into cnpj.situacao_cadatral_motivo values (24, "POR EMISSÃO CERTIDÃO NEGATIVA");
insert into cnpj.situacao_cadatral_motivo values (25, "CERTIDÃO POSITIVA COM EFEITO DE NEGATIVA");
insert into cnpj.situacao_cadatral_motivo values (26, "IRREGULARIDADE DE PAGAMENTO");
insert into cnpj.situacao_cadatral_motivo values (27, "IRREGULARIDADE DE RECOLHIMENTO E EXIGIBILIDADE SUSPENSA");
insert into cnpj.situacao_cadatral_motivo values (28, "TRANSFERÊNCIA FILIAL CONDIÇÃO MATRIZ");
insert into cnpj.situacao_cadatral_motivo values (29, "AGUARDANDO CONF. DE DIRPJ/DIPJ");
insert into cnpj.situacao_cadatral_motivo values (30, "ANR - AGUARDANDO CONF. DE DIRPJ/DIPJ");
insert into cnpj.situacao_cadatral_motivo values (31, "EXTINÇÃO DA FILIAL");
insert into cnpj.situacao_cadatral_motivo values (32, "INEXISTENTE DE FATO – ADE/COSAR");
insert into cnpj.situacao_cadatral_motivo values (33, "TRANSFERÊNCIA DO ÓRGÃO LOCAL A CONDIÇÃO DE FILIAL DO ÓRGÃO REGIONAL");
insert into cnpj.situacao_cadatral_motivo values (34, "ANULAÇÃO DE INSCRIÇÃO INDEVIDA");
insert into cnpj.situacao_cadatral_motivo values (35, "EMPRESA ESTRANGEIRA AGUARDANDO DOCUMENTAÇÃO");
insert into cnpj.situacao_cadatral_motivo values (36, "PRÁTICA IRREGULAR DE OPERAÇÃO DE COMERCIO EXTERIOR");
insert into cnpj.situacao_cadatral_motivo values (37, "BAIXA DE PRODUTOR RURAL");
insert into cnpj.situacao_cadatral_motivo values (38, "BAIXA DEFERIDA PELA RFB AGUARDANDO ANALISE DO CONVENENTE");
insert into cnpj.situacao_cadatral_motivo values (39, "BAIXA DEFERIDA PELA RFB E INDEFERIDA PELO CONVENENTE");
insert into cnpj.situacao_cadatral_motivo values (40, "BAIXA INDEFERIDA PELA RFB E AGUARDANDO ANALISE DO CONVENENTE");
insert into cnpj.situacao_cadatral_motivo values (41, "BAIXA INDEFERIDA PELA RFB E DEFERIDA PELO CONVENENTE");
insert into cnpj.situacao_cadatral_motivo values (42, "BAIXA INDEFERIDA PELA RFB E SEFIN, AGUARDANDO ANALISE SEFAZ");
insert into cnpj.situacao_cadatral_motivo values (43, "BAIXA DEFERIDA PELA RFB, AGUARDANDO ANALISE DA SEFAZ E INDEFERIDA PELA SEFIN");
insert into cnpj.situacao_cadatral_motivo values (44, "BAIXA DEFERIDA PELA RFB E SEFAZ, AGUARDANDO ANALISE SEFIN");
insert into cnpj.situacao_cadatral_motivo values (45, "BAIXA DEFERIDA PELA RFB, AGUARDANDO ANALISE DA SEFIN E INDEFERIDA PELA SEFAZ");
insert into cnpj.situacao_cadatral_motivo values (46, "BAIXA DEFERIDA PELA RFB E SEFAZ E INDEFERIDA PELA SEFIN");
insert into cnpj.situacao_cadatral_motivo values (47, "BAIXA DEFERIDA PELA RFB E SEFIN E INDEFERIDA PELA SEFAZ");
insert into cnpj.situacao_cadatral_motivo values (48, "BAIXA INDEFERIDA PELA RFB, AGUARDANDO ANALISE SEFAZ E DEFERIDA PELA SEFIN");
insert into cnpj.situacao_cadatral_motivo values (49, "BAIXA INDEFERIDA PELA RFB, AGUARDANDO ANALISE DA SEFAZ E INDEFERIDA PELA SEFIN");
insert into cnpj.situacao_cadatral_motivo values (50, "BAIXA INDEFERIDA PELA RFB, DEFERIDA PELA SEFAZ E AGUARDANDO ANALISE DA SEFIN");
insert into cnpj.situacao_cadatral_motivo values (51, "BAIXA INDEFERIDA PELA RFB E SEFAZ, AGUARDANDO ANALISE DA SEFIN");
insert into cnpj.situacao_cadatral_motivo values (52, "BAIXA INDEFERIDA PELA RFB, DEFERIDA PELA SEFAZ E INDEFERIDA PELA SEFIN");
insert into cnpj.situacao_cadatral_motivo values (53, "BAIXA INDEFERIDA PELA RFB E SEFAZ E DEFERIDA PELA SEFIN");
insert into cnpj.situacao_cadatral_motivo values (54, "BAIXA - TRATAMENTO DIFERENCIADO DADO AS ME E EPP (LEI COMPLEMENTAR NUMERO 123/2006)");
insert into cnpj.situacao_cadatral_motivo values (55, "DEFERIDO PELO CONVENENTE, AGUARDANDO ANALISE DA RFB");
insert into cnpj.situacao_cadatral_motivo values (60, "ARTIGO 30, VI, DA IN 748/2007");
insert into cnpj.situacao_cadatral_motivo values (61, "INDICIO INTERPOS. FRAUDULENTA");
insert into cnpj.situacao_cadatral_motivo values (62, "FALTA DE PLURALIDADE DE SOCIOS");
insert into cnpj.situacao_cadatral_motivo values (63, "OMISSÃO DE DECLARAÇÕES");
insert into cnpj.situacao_cadatral_motivo values (64, "LOCALIZAÇÃO DESCONHECIDA");
insert into cnpj.situacao_cadatral_motivo values (66, "INAPTIDÃO");
insert into cnpj.situacao_cadatral_motivo values (67, "REGISTRO CANCELADO");
insert into cnpj.situacao_cadatral_motivo values (70, "ANULAÇÃO POR NÃO CONFIRMADO ATO DE REGISTRO DO MEI NA JUNTA COMERCIAL");
insert into cnpj.situacao_cadatral_motivo values (71, "INAPTIDÃO (LEI 11.941/2009 ART.54)");
insert into cnpj.situacao_cadatral_motivo values (72, "DETERMINAÇÃO JUDICIAL");
insert into cnpj.situacao_cadatral_motivo values (73, "OMISSÃO CONTUMAZ");
insert into cnpj.situacao_cadatral_motivo values (74, "INCONSISTÊNCIA CADASTRAL");
insert into cnpj.situacao_cadatral_motivo values (80, "BAIXA REGISTRADA NA JUNTA, INDEFERIDA NA RFB");
