package net.cartola.receita.cnpj.model;

/**
 * @see https://cnae.ibge.gov.br/?view=estrutura
 * @author Murilo Moraes Tuvani
 *
 */
public enum CnaeSecao {
	
	AGRICULTURA_PECUARIA_PRODUCAO_FLORESTAL_PESCA_E_AQUICULTURA("A",1,3,"AGRICULTURA, PECUÁRIA, PRODUÇÃO FLORESTAL, PESCA E AQÜICULTURA"),
	INDUSTRIAS_EXTRATIVAS("B",5,9,"INDÚSTRIAS EXTRATIVAS"),
	INDUSTRIAS_DE_TRANSFORMACAO("C",10,33,"INDÚSTRIAS DE TRANSFORMAÇÃO"),
	ELETRICIDADE_E_GAS("D",35,35,"ELETRICIDADE E GÁS"),
	AGUA_ESGOTO_ATIVIDADES_DE_GESTAO_DE_RESIDUOS_E_DESCONTAMINACAO("E",36,39,"ÁGUA, ESGOTO, ATIVIDADES DE GESTÃO DE RESÍDUOS E DESCONTAMINAÇÃO"),
	CONSTRUCAO("F",41,43,"CONSTRUÇÃO"),
	COMERCIO_REPARACAO_DE_VEICULOS_AUTOMOTORES_E_MOTOCICLETAS("G",45,47,"COMÉRCIO; REPARAÇÃO DE VEÍCULOS AUTOMOTORES E MOTOCICLETAS"),
	TRANSPORTE_ARMAZENAGEM_E_CORREIO("H",49,53,"TRANSPORTE, ARMAZENAGEM E CORREIO"),
	ALOJAMENTO_E_ALIMENTACAO("I",55,56,"ALOJAMENTO E ALIMENTAÇÃO"),
	INFORMACAO_E_COMUNICACAO("J",58,63,"INFORMAÇÃO E COMUNICAÇÃO"),
	ATIVIDADES_FINANCEIRAS_DE_SEGUROS_E_SERVICOS_RELACIONADOS("K",64,66,"ATIVIDADES FINANCEIRAS, DE SEGUROS E SERVIÇOS RELACIONADOS"),
	ATIVIDADES_IMOBILIARIAS("L",68,68,"ATIVIDADES IMOBILIÁRIAS"),
	ATIVIDADES_PROFISSIONAIS_CIENTIFICAS_E_TECNICAS("M",69,75,"ATIVIDADES PROFISSIONAIS, CIENTÍFICAS E TÉCNICAS"),
	ATIVIDADES_ADMINISTRATIVAS_E_SERVICOS_COMPLEMENTARES("N",77,82,"ATIVIDADES ADMINISTRATIVAS E SERVIÇOS COMPLEMENTARES"),
	ADMINISTRACAO_PUBLICA_DEFESA_E_SEGURIDADE_SOCIAL("O",84,84,"ADMINISTRAÇÃO PÚBLICA, DEFESA E SEGURIDADE SOCIAL"),
	EDUCACAO("P",85,85,"EDUCAÇÃO"),
	SAUDE_HUMANA_E_SERVICOS_SOCIAIS("Q",86,88,"SAÚDE HUMANA E SERVIÇOS SOCIAIS"),
	ARTES_CULTURA_ESPORTE_E_RECREACAO("R",90,93,"ARTES, CULTURA, ESPORTE E RECREAÇÃO"),
	OUTRAS_ATIVIDADES_DE_SERVICOS("S",94,96,"OUTRAS ATIVIDADES DE SERVIÇOS"),
	SERVICOS_DOMESTICOS("T",97,97,"SERVIÇOS DOMÉSTICOS"),
	ORGANISMOS_INTERNACIONAIS_E_OUTRAS_INSTITUICOES_EXTRATERRITORIAIS("U",99,99,"ORGANISMOS INTERNACIONAIS E OUTRAS INSTITUIÇÕES EXTRATERRITORIAIS");

	private final String secao;
	private final int divisaoInicial;
	private final int divisaoFinal;
	private final String denominacao;
	
	CnaeSecao(String secao, int ci, int cf, String descricao)  {
		this.secao = secao;
		this.divisaoInicial = ci;
		this.divisaoFinal = cf;
		this.denominacao = descricao;
	}


	public String getSecao() {
		return secao;
	}

	public int getDivisaoInicial() {
		return divisaoInicial;
	}

	public int getDivisaoFinal() {
		return divisaoFinal;
	}

	public String getDenominacao() {
		return denominacao;
	}

}
